name: CI

on: [push, pull_request]

jobs:
    unit-tests:
        name: Unit tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v1

            - name: Install composer dependencies
              run: composer install --prefer-dist --ignore-platform-reqs

            - name: Run PHPUnit unit tests
              run: php7.4 vendor/bin/phpunit